### ISSUE TITLE
Needs to be removed

### ISSUE THREAD

**Issue by raultomescu** [SvitlanaShepitsena/itsquiz-wall#13]
`2. cp etc/client-config.json.sample etc/client-config.json (by default connect to production REST API)` needs to be removed, right? Since you already got a `client-config.json` file there, and it is different.

**Comment by AndriyShepitsen** [comment]
Raul, we are in the process of switching from  WebbyLab/itsquiz-wall where they have a separate authentication backend to the locally implemented passport auth. You may leave sample after copying it is not used anywhere besides initial copy to client-config.json. Sorry for inconvenience - will do our best to clean app by the eod.

**Comment by raultomescu** [comment]
That's great. Thanks. :+1:
